

#[badge.examples]
#values = ["List of practical use cases"]


# Some Examples
# Data Source Disclosed
[badge]
badge-name = "Data Source Disclosed"
description = "Indicates that this visualization has one or more disclosed data sources."
intent = "Confirmation"
type = "Data"

[badge.attributes]
data-type = "Binary"
values = []
unit = ""

[badge.relations]
mutual-exclusive = ["No Data Source Disclosed"]
dependencies = []
complements = ["Data Source Citation"]

[badge.scope]
value = "WHOLE PAGE"

[badge.inferred]
value = false


# Contains Predictions
[badge]
badge-name = "Contains Predictions"
description = "Indicates that the entire or parts of the data are future predictions, implying uncertainty."
intent = "Confirmation"
type = "Analysis"

[badge.attributes]
data-type = "Ordinal"
values = ["No predictions", "Some predictions", "Entire dataset is a prediction"]
unit = ""

[badge.relations]
mutual-exclusive = []
dependencies = ["Contains Modeled Data"]
complements = ["Uncertainty Shown"]

[badge.scope]
value = "?"

[badge.inferred]
value = false

# Truncated Axis
[badge]
badge-name = "Truncated Axis"
description = "Indicates that the axis in the chart is truncated and does not start at zero."
intent = "Warning"
type = "Visual Encoding"

[badge.attributes]
data-type = "Binary"
values = []
unit = ""

[badge.relations]
mutual-exclusive = ["Axis Starts at Zero"]
dependencies = []
complements = []

[badge.scope]
value = "Local"

[badge.inferred]
value = false

[badge.examples]
values = ["A bar chart where the y-axis starts at 50 instead of 0."]

