[binaryBadge]
badge-name = "string"
description = "string"
intent = "Confirmation | Warning | Information"
type = "Data | Analysis | Context | Interaction | Visual Encoding"
tags = []

group = "broader category (e.g., Data Cleaning, Target Audience)"

[badge.attributes]
data-type = "Binary | Ordinal | Categorical | Quantity | User-Defined"
values = ["optional list of possible values"]
unit = "string"  # (if applicable, e.g., % missing data)

[badge.relations]
mutual-exclusive = ["list of conflicting badges"]
dependencies = ["list of required badges or justifications"]
complements = ["list of badges that reinforce each other"]
inferred-from = ["badges that can automatically generate this badge"]

[badge.scope]
value = "Page | Chart | Data Point"

display-behavior = ["on-hover", "on-click", "custom"]

