[BinaryBadge]
label = "<TEXT>"
link = "<URL>"
tooltip = "<TEXT>"
type = "<Data | Analysis | Context | Interaction | Visual Encoding>"
intent = "<GOOD | NEUTRAL | BAD | DEPENDENT>"


[OrdinalBadge_schema1]
label   = "<TEXT>"
link    = "<URL>"
tooltip = "<TEXT>"
type    = "<Data | Analysis | Context | Interaction | Visual Encoding>"
intent  = "<GOOD | NEUTRAL | BAD | DEPENDENT>"

[[OrdinalBadge.values]]
value = "<STRING>"
color = "<COLOR>"

[[OrdinalBadge.values]]
value = "<STRING>"
color = "<COLOR>"

# ... additional value entries as needed

[OrdinalBadge_schema2]
label = "<TEXT>"
link = "<URL>"
tooltip = "<TEXT>"
type = "<Data | Analysis | Context | Interaction | Visual Encoding>"
intent = "<GOOD | NEUTRAL | BAD | DEPENDENT>"
[[badge.values]]
value_1 = "<STRING>"
intent_1 = "<GOOD | NEUTRAL | BAD | DEPENDENT>"
value_2 = "<STRING>"
intent_2 = "<GOOD | NEUTRAL | BAD | DEPENDENT>"



[CategoricalBadge]
label = "<TEXT>"
link = "<URL>"
tooltip = "<TEXT>"
type = "<Data | Analysis | Context | Interaction | Visual Encoding>"
[[CategoricalBadge.Values]]
name = "<TEXT>"
link = "<URL>"

[QuantitativeBadge]
label = "<TEXT>"
tooltip = "<TEXT>"
link = "<URL>"
type = "<Data | Analysis | Context | Interaction | Visual Encoding>"
value = <NUMBER>
unit = "<TEXT>"

